stages:
  - init
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  TERRAFORM_MODULE_SYSTEM: local

init:
  stage: init
  image: hashicorp/terraform:light
  script:
    - terraform init

plan:
  stage: plan
  image: hashicorp/terraform:light
  script:
    - terraform plan

apply:
  stage: apply
  image: hashicorp/terraform:light
  when: manual
  script:
    - terraform apply -auto-approve